require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpmsController do

  # This should return the minimal set of attributes required to create a valid
  # Spm. As you add validations to Spm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "spm_ref" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpmsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all spms as @spms" do
      spm = Spm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spms).should eq([spm])
    end
  end

  describe "GET show" do
    it "assigns the requested spm as @spm" do
      spm = Spm.create! valid_attributes
      get :show, {:id => spm.to_param}, valid_session
      assigns(:spm).should eq(spm)
    end
  end

  describe "GET new" do
    it "assigns a new spm as @spm" do
      get :new, {}, valid_session
      assigns(:spm).should be_a_new(Spm)
    end
  end

  describe "GET edit" do
    it "assigns the requested spm as @spm" do
      spm = Spm.create! valid_attributes
      get :edit, {:id => spm.to_param}, valid_session
      assigns(:spm).should eq(spm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Spm" do
        expect {
          post :create, {:spm => valid_attributes}, valid_session
        }.to change(Spm, :count).by(1)
      end

      it "assigns a newly created spm as @spm" do
        post :create, {:spm => valid_attributes}, valid_session
        assigns(:spm).should be_a(Spm)
        assigns(:spm).should be_persisted
      end

      it "redirects to the created spm" do
        post :create, {:spm => valid_attributes}, valid_session
        response.should redirect_to(Spm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spm as @spm" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spm.any_instance.stub(:save).and_return(false)
        post :create, {:spm => { "spm_ref" => "invalid value" }}, valid_session
        assigns(:spm).should be_a_new(Spm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spm.any_instance.stub(:save).and_return(false)
        post :create, {:spm => { "spm_ref" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spm" do
        spm = Spm.create! valid_attributes
        # Assuming there are no other spms in the database, this
        # specifies that the Spm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Spm.any_instance.should_receive(:update).with({ "spm_ref" => "MyString" })
        put :update, {:id => spm.to_param, :spm => { "spm_ref" => "MyString" }}, valid_session
      end

      it "assigns the requested spm as @spm" do
        spm = Spm.create! valid_attributes
        put :update, {:id => spm.to_param, :spm => valid_attributes}, valid_session
        assigns(:spm).should eq(spm)
      end

      it "redirects to the spm" do
        spm = Spm.create! valid_attributes
        put :update, {:id => spm.to_param, :spm => valid_attributes}, valid_session
        response.should redirect_to(spm)
      end
    end

    describe "with invalid params" do
      it "assigns the spm as @spm" do
        spm = Spm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spm.any_instance.stub(:save).and_return(false)
        put :update, {:id => spm.to_param, :spm => { "spm_ref" => "invalid value" }}, valid_session
        assigns(:spm).should eq(spm)
      end

      it "re-renders the 'edit' template" do
        spm = Spm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spm.any_instance.stub(:save).and_return(false)
        put :update, {:id => spm.to_param, :spm => { "spm_ref" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spm" do
      spm = Spm.create! valid_attributes
      expect {
        delete :destroy, {:id => spm.to_param}, valid_session
      }.to change(Spm, :count).by(-1)
    end

    it "redirects to the spms list" do
      spm = Spm.create! valid_attributes
      delete :destroy, {:id => spm.to_param}, valid_session
      response.should redirect_to(spms_url)
    end
  end

end
